# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['recorder_standalone.py'],
    pathex=[],
    binaries=[],
    datas=[('config/default_config.yaml', 'config')],
    hiddenimports=[
        'win32gui',
        'win32process',
        'win32api',
        'win32con',
        'psutil',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'numpy',
        'pywt',
        'lifetrace_backend',
        'lifetrace_backend.utils',
        'lifetrace_backend.recorder',
        'lifetrace_backend.config',
        'lifetrace_backend.logging_config',
        'lifetrace_backend.app_mapping',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=True,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [('v', None, 'OPTION')],
    name='LifeTrace_Recorder',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
