# LifeTrace 默认配置文件

# 基础目录配置
base_dir: 'data'
database_path: 'data/lifetrace.db'
screenshots_dir: 'screenshots'

# 服务器配置
server:
  host: '127.0.0.1'
  port: 8840

# 录制配置
record:
  interval: 1  # 截图间隔（秒）
  screens: 'all'  # 截图屏幕：all 或屏幕编号列表
  auto_exclude_self: true  # 自动排除LifeTrace自身窗口
  blacklist:
    enabled: false  # 是否启用黑名单功能
    apps: []  # 应用黑名单，使用友好名称，例如: ["微信", "QQ", "钉钉"]
    windows: []  # 窗口标题黑名单，例如: ["记事本", "计算器"]

# OCR配置
ocr:
  enabled: true
  use_gpu: false
  language: ['ch', 'en']
  check_interval: 5  # 数据库检查间隔（秒）
  confidence_threshold: 0.5

# 存储配置
storage:
  max_days: 30  # 数据保留天数
  deduplicate: true  # 启用去重

# 处理配置
processing:
  batch_size: 10
  queue_size: 100

# 一致性检查配置
consistency_check:
  interval: 300  # 一致性检查间隔（秒）

# 向量数据库配置
vector_db:
  enabled: true  # 启用向量数据库
  collection_name: 'lifetrace_ocr'  # 集合名称
  embedding_model: 'shibing624/text2vec-base-chinese'  # 嵌入模型
  rerank_model: 'BAAI/bge-reranker-base'  # 重排序模型
  persist_directory: 'vector_db'  # 持久化目录
  chunk_size: 512  # 文本块大小
  chunk_overlap: 50  # 文本块重叠
  batch_size: 32  # 批处理大小
  auto_sync: true  # 自动同步
  sync_interval: 300  # 同步间隔（秒）

# 同步服务配置
sync_service:
  enable_file_monitor: true  # 启用文件监控
  enable_consistency_check: true  # 启用一致性检查
  consistency_check_interval: 300  # 一致性检查间隔（秒）
  vector_sync_interval: 600  # 向量数据库同步间隔（秒）
  file_monitor_delay: 2.0  # 文件监控延迟（秒）
  cleanup_orphaned_files: true  # 清理孤立文件
  log_level: 'INFO'  # 日志级别

# 心跳监控配置
heartbeat:
  enabled: true  # 启用心跳监控
  interval: 1.0  # 心跳记录间隔（秒）- 每隔多长时间记录一次心跳
  timeout: 15  # 心跳超时时间（秒）- 超过此时间未收到心跳则认为服务异常
  check_interval: 30  # 心跳检查间隔（秒）- 每隔多长时间检查一次心跳状态
  log_dir: 'data/logs/heartbeat'  # 心跳日志目录 - 心跳日志文件存储位置
  log_rotation:
    max_size_mb: 10  # 单个日志文件最大大小（MB）- 日志文件达到此大小时自动轮转
    max_files: 5  # 最大日志文件数量 - 保留的历史日志文件数量
    auto_cleanup: true  # 自动清理旧日志 - 超过最大文件数时自动删除最旧的日志
  auto_restart:
    enabled: true  # 启用自动重启 - 检测到服务异常时是否自动重启
    max_attempts: 30  # 最大重启尝试次数 - 连续重启失败的最大次数
    delay: 1  # 重启延迟（秒）- 重启前等待的时间
    reset_count_interval: 3600  # 重启计数重置间隔（秒）- 每隔此时间重置重启计数器
  # UDP心跳配置
  udp:
    enabled: true  # 启用UDP心跳机制
    port: 9999  # UDP心跳接收端口
    host: '127.0.0.1'  # UDP心跳接收地址
    buffer_size: 1024  # UDP接收缓冲区大小

# 日志配置
logging:
  main_log_level: 'INFO'
  server_log_level: 'INFO'
  recorder_log_level: 'INFO'
  processor_log_level: 'INFO'
  sync_log_level: 'INFO'
  consistency_log_level: 'INFO'
  file_monitor_log_level: 'INFO'
