# RapidOCR 配置文件 - 性能优化版本
# 用于解决PyInstaller打包后配置文件缺失的问题
# 针对打包后性能进行优化

Global:
  use_angle_cls: false  # 关闭角度分类器以提升速度
  print_verbose: false
  min_height: 20        # 降低最小高度阈值

Det:
  use_cuda: false
  limit_side_len: 960   # 增加图像尺寸限制以提高精度
  limit_type: min
  thresh: 0.4           # 提高阈值以减少误检
  box_thresh: 0.6       # 提高框阈值
  max_candidates: 500   # 减少候选框数量以提升速度
  unclip_ratio: 1.8     # 优化展开比例
  use_dilation: false
  score_mode: fast

Cls:
  use_cuda: false
  cls_thresh: 0.8       # 降低分类阈值

Rec:
  use_cuda: false
  rec_batch_num: 8      # 增加批处理数量以提升效率

# 外部模型文件路径配置（用于PyInstaller打包优化）
Models:
  det_model_path: "models/ch_PP-OCRv4_det_infer.onnx"
  rec_model_path: "models/ch_PP-OCRv4_rec_infer.onnx"
  cls_model_path: "models/ch_ppocr_mobile_v2.0_cls_infer.onnx"
